# This workflow performs the following:
# 1. Deploys on Ubuntu, Windows, and MacOS
# 2. Installs Python Dependences (v. 3.9 and 3.10)
# 3. Lints Python files with flake8 and Black
# 4. Runs tests using pytest

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }} # References environments to run

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest] # Defines environments to deploy on
        python-version: [ '3.9', '3.10' ] # Defines versions of Python that should be built

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }} # References Python Versions
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --verbose flake8 black pytest
        python -m pip install --verbose -r python_package_exercise/python_package_exercise/requirements.txt
    #bash -c "if [ -f requirements.txt ]; then pip install --verbose -r requirements.txt; fi"

    #Check installed packages
    - name: List installed packages
      run: |
        pip list  

    - uses: pre-commit/action@v3.0.1  
    # Implementation found at https://black.readthedocs.io/en/stable/integrations/github_actions.html

